name: CI/CD

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run Build Task
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            git pull
            git reset --hard ${{ github.ref_name }}
            docker-compose down ${{ secrets.DOCKER_IMAGE_NAME }}
            docker-compose build ${{ secrets.DOCKER_IMAGE_NAME }}
            docker-compose up -d ${{ secrets.DOCKER_IMAGE_NAME }}
